export default {
    'en-us': {
        barText: 'Blog',
        postsTitle: 'All posts',
        list: [
            {
                title: 'Dubbo Admin service test',
                author: '@nzomkxia',
                dateStr: 'August 26th, 2019',
                desc: 'This article introduces how to make service test with Dubbo',
                link: '/en-us/blog/service-test.html',
            },
            {
                title: 'Implementation background and practice of Dubbo server asynchronous interface',
                author: '@JeffLv',
                dateStr: 'Feb 20th, 2019',
                desc: 'Implementation background and practice of Dubbo server asynchronous interface',
                link: '/en-us/blog/dubboAsync_server.html',
            },
            {
                title: 'Implementation background and practice of Dubbo client asynchronous interface',
                author: '@JeffLv',
                dateStr: 'Feb 20th, 2019',
                desc: 'Implementation background and practice of Dubbo client asynchronous interface',
                link: '/en-us/blog/dubboAsync_client.html',
            },
            {
                title: 'How to use Fescar to ensure consistency between Dubbo Microservices',
                author: '@slievrly',
                dateStr: 'Jan 17th, 2019',
                desc: 'This blog describes details of using Fescar to ensure consistency between Dubbo Microservices',
                link: '/en-us/blog/dubbo-fescar.html',
            },
            {
                title: 'Prepare an Apache Release',
                author: 'Jun Liu',
                dateStr: 'Sep 2nd, 2018',
                desc: 'How to prepare an Apache release',
                link: '/en-us/blog/prepare-an-apache-release.html',
            },
            {
                title: 'How to implement a fully asynchronous calls chain based on Dubbo',
                author: '@Siqi Zhuo',
                dateStr: 'Aug 13th, 2018',
                desc: 'Introduce the new feature of implementing the full asynchronous programming in Dubbo 2.7.0, mainly about previous asynchronous method before 2.6.x versions, enhancement in version 2.7.0 and a few examples to demonstrate its usage',
                link: '/en-us/blog/dubbo-new-async.html',
            },
            {
                title: 'Generic invoke of Dubbo',
                author: '@ChasePGit',
                dateStr: 'August 14th，2018',
                desc: 'This blog describes details of Dubbo generic invoke including usage and examples.',
                link: '/en-us/blog/dubbo-generic-invoke.html',
            },
            {
                title: 'Several ways about synchronous/asynchronous invoke of Dubbo',
                author: '@Hou Yongxu',
                dateStr: 'August 14th，2018',
                desc: 'This blog describes several ways about synchronous/asynchronous invoke of Dubbo',
                link: '/en-us/blog/dubbo-invoke.html',
            },
            {
                title: 'Implementation of cross-language calls by dubbo2.js',
                author: '@Stella0824',
                dateStr: 'August 14th, 2018',
                desc: 'This blog describes how to use dubbo2.js for cross-language calls',
                link: '/en-us/blog/dubbo2-js.html',
            },
            {
                title: 'The basic usage of Dubbo Provider configuration',
                author: '@Ziyang-Wu',
                dateStr: 'August 14th, 2018',
                desc: 'This blog describes how to configure Dubbo Provider in detail from XML, properties, annotation and API configurations. ',
                link: '/en-us/blog/dubbo-basic-usage-dubbo-provider-configuration.html',
            },
            {
                title: 'How to prepare an Apache release',
                author: '@smilechenjia',
                dateStr: 'August 14th, 2018',
                desc: 'This blog describes the full flow of Apache release in detail from how to install local environment and start vote.',
                link: '/en-us/blog/prepare-an-apache-release.html',
            },
            {
                title: 'Source code analysis of spring-boot+Dubbo App start and stop',
                author: '@noahziheng',
                dateStr: 'August 14th, 2018',
                desc: 'Dubbo Spring Boot project is dedicated to simplifying the development of the Dubbo RPC framework in the Spring Boot application.',
                link: '/en-us/blog/spring-boot-dubbo-start-stop-analysis.html',
            },
            {
                title: 'Dubbo extensible mechanism source code analysis',
                author: '@cuteSoul',
                dateStr: 'August 14th, 2018',
                desc: 'This blog will go deep into the source code of Dubbo extension mechanism.',
                link: '/en-us/blog/introduction-to-dubbo-spi-2.html',
            },
            {
                title: 'Manipulating Services Dynamically via QoS',
                author: '@Wendell Hu (@wendzhue)',
                dateStr: 'August 14th, 2018',
                desc: 'This blog introduces how to use QoS of Dubbo to configure services dynamically, and QoS\'s parameters and ways to configure',
                link: '/en-us/blog/introduction-to-dubbo-qos.html',
            },
            {
                title: 'Dubbo Loadbalance',
                author: '@CyanCity, @liaoandi',
                dateStr: 'August 10th, 2018',
                desc: 'This blog introduces serval loadbalancing concepts and Dubbo loadbalancing strategy implementation.',
                link: '/en-us/blog/dubbo-loadbalance.html',
            },
            {
                title: 'Sentinel: The flow sentinel of Dubbo services',
                author: '@Eric Zhao',
                dateStr: 'July 27th, 2018',
                desc: 'This blog introduces to the Sentinel and its best practice with Dubbo services. Sentinel is a powerful library that takes "flow" as the breakthrough point, and covers multiple fields including flow control, circuit breaking and load protection to guarantee service stability.',
                link: '/en-us/blog/sentinel-introduction-for-dubbo.html',
            },
            {
                title: 'Tracking with Pinpoint',
                author: '@majinkai',
                dateStr: 'July 12th, 2018',
                desc: 'Call chain tracking and performance monitoring for Dubbo distributed applications using Pinpoint',
                link: '/en-us/blog/pinpoint.html',
            },
            {
                title: 'The first Dubbo meetup has been held in Beijing',
                author: 'Huxing Zhang',
                dateStr: 'May 12th，2018',
                desc: 'The first Dubbo meetup has successfully been held in Beijing, over 400+ people were present. What a great event! ',
                link: '/en-us/blog/dubbo-meetup-beijing-may-12th-2018.html',
            },
            {
                title: 'The ApacheCon NA schedule has been announced',
                author: '@Huxing Zhang',
                dateStr: 'May 2nd，2018',
                desc: 'Ian Luo and Jun Liu will talk about "Introducing Apache Dubbo(Incubating): What is Dubbo and How it Works" at ApacheCon NA this year in Montréal!',
                link: '/en-us/blog/apachecon-na-2018.html',
            },
            {
                title: 'The GSoC (Google Summer of Code) 2018 projects has been announced',
                author: '@Huxing Zhang',
                dateStr: 'April 25th，2018',
                desc: 'Raghu Reddy\'s project "Extending Serialization protocols support for Apache Dubbo" has been accepted! Congratulations!',
                link: '/en-us/blog/gsoc-2018.html',
            },
            {
                title: 'Dubbo roadmap is announced in QCon Beijing 2018',
                author: '@Huxing Zhang',
                dateStr: 'April 22th，2018',
                desc: 'Ian Luo has delivered a great talk at QCon Beijing 2018, where the roadmap of Dubbo has also be announced',
                link: '/en-us/blog/qcon-beijing-2018.html',
            },
            {
                title: 'Introduction to Dubbo spi ',
                author: '@wangxuekui',
                dateStr: 'August 9th, 2018',
                desc: 'We have introduction to Dubbo spi.',
                link: '/en-us/blog/introduction-to-dubbo-spi.html',
            },
            {
                title: 'Use annotation in Dubbo',
                author: '@Ge Shao',
                dateStr: 'August 7nd，2018',
                desc: 'This blog introduces how to use annotations',
                link: '/en-us/blog/dubbo-annotation.html',
            },
            {
                title: 'Using Zookeeper in Dubbo',
                author: '@Mani',
                dateStr: 'August 7th，2018',
                desc: 'This blog introduces how to use Zookeeper in Dubbo',
                link: '/en-us/blog/dubbo-zk.html',
            },
            {
                title: 'Your First Dubbo filter',
                author: '@nzomkxia',
                dateStr: 'July 1st, 2018',
                desc: 'This blog introduces the filter mechanism in Dubbo, and how to inplement a Dubbo Filter',
                link: '/en-us/blog/first-dubbo-filter.html',
            },
            {
                title: 'Your First Dubbo Demo',
                author: '@Yang Xinru',
                dateStr: 'August 7th，2018',
                desc: 'Your First Dubbo Demo',
                link: '/en-us/blog/dubbo-101.html',
            },
            {
                title: 'Dubbo protocol',
                author: '@catxu',
                dateStr: 'Oct 11th, 2019',
                desc: 'This article introduces the common protocol mode and the design of Dubbo protocol',
                link: '/en-us/blog/dubbo-protocol.html',
            }
        ]
    },
    'zh-cn': {
        barText: '博客',
        postsTitle: '所有文章',
        list: [
            {
                title: '浅谈 RPC',
                author: '@caojiele',
                dateStr: 'August 1th, 2019',
                desc: '介绍 RPC 基本原理和实现方式',
                link: '/zh-cn/blog/rpc-introduction.html',
            },
            {
                title: '在DockerHub发布Dubbo Admin镜像',
                author: '@htynkn',
                dateStr: 'May 23th, 2019',
                desc: '介绍如何在DockerHub上发布Dubbo Admin镜像',
                link: '/zh-cn/blog/build-new-docker-image-in-dockerhub.html',
            },
            {
                title: '研究 Dubbo 网卡地址注册时的一点思考',
                author: '@lexburner',
                dateStr: 'Apr 30th, 2019',
                desc: '研究 Dubbo 网卡地址注册时的一点思考',
                link: '/zh-cn/blog/dubbo-network-interfaces.html',
            },
            {
                title: 'Dubbo 本地存根和本地伪装',
                author: '@beiwei30',
                dateStr: 'Apr 9th, 2019',
                desc: '介绍本地伪装、本地存根的概念以及如何开发',
                link: '/zh-cn/blog/dubbo-stub-mock.html',
            },
            {
                title: 'Dubbo2.7 三大新特性详解',
                author: '@lexburner',
                dateStr: 'Mar 22th, 2019',
                desc: '异步化改造,三大中心改造,服务治理增强',
                link: '/zh-cn/blog/dubbo-27-features.html',
            },
            {
                title: 'Dubbo 本地调用',
                author: '@beiwei30',
                dateStr: 'Mar 20th, 2019',
                desc: 'Dubbo 本地调用的概念和用法',
                link: '/zh-cn/blog/dubbo-local-call.html',
            },
            {
                title: 'Dubbo优雅停机介绍',
                author: '@guohao',
                dateStr: 'Feb 22th, 2019',
                desc: 'Dubbo优雅停机的实现背景和实践',
                link: '/zh-cn/blog/dubbo-gracefully-shutdown.html',
            },
            {
                title: 'Dubbo客户端异步接口的实现背景和实践',
                author: '@JeffLv',
                dateStr: 'Feb 20th, 2019',
                desc: 'Dubbo客户端异步接口的实现背景和实践',
                link: '/zh-cn/blog/dubboAsync_client.html',
            },
            {
                title: 'Dubbo服务端异步接口的实现背景和实践',
                author: '@JeffLv',
                dateStr: 'Feb 20th, 2019',
                desc: 'Dubbo服务端异步接口的实现背景和实践',
                link: '/zh-cn/blog/dubboAsync_server.html',
            },
            {
                title: 'Dubbo Admin服务测试介绍',
                author: '@nzomkxia',
                dateStr: 'Jan 29th, 2019',
                desc: '本文介绍了新版本的Dubbo Admin的服务测试功能',
                link: '/zh-cn/blog/service-test.html',
            },
            {
                title: '新版本Dubbo Admin介绍',
                author: '@nzomkxia',
                dateStr: 'Jan 28th, 2019',
                desc: '本文介绍了新版本的Dubbo Admin的设计和功能',
                link: '/zh-cn/blog/dubbo-admin.html',
            },
            {
                title: '如何使用Fescar保证Dubbo微服务间的一致性',
                author: '@slievrly',
                dateStr: 'Jan 17th, 2019',
                desc: '本文详细介绍了如何使用Fescar保证Dubbo微服务间的一致性',
                link: '/zh-cn/blog/dubbo-fescar.html',
            },
            {
                title: 'Dubbo 注解驱动',
                author: '@mercyblitz',
                dateStr: 'Jan 2nd, 2019',
                desc: '本文介绍 Dubbo 编程模型：注册驱动，包括设计思考以及使用方法',
                link: '/zh-cn/blog/dubbo-annotation-driven.html',
            },
            {
                title: 'Dubbo 外部化配置',
                author: '@mercyblitz',
                dateStr: 'Jan 2nd, 2019',
                desc: '本文介绍 Dubbo 编程模型：外部化配置，包括外部化配置注解以及单或多 Dubbo 配置 Bean 绑定',
                link: '/zh-cn/blog/dubbo-externalized-configuration.html',
            },
            {
                title: 'Dubbo 注册中心 Nacos 整合',
                author: '@mercyblitz',
                dateStr: 'Jan 2nd, 2019',
                desc: '本文介绍 Dubbo 如何整合注册中心 Nacos，包括 Nacos 控制台使用',
                link: '/zh-cn/blog/dubbo-registry-nacos-integration.html',
            },
            {
                title: 'Dubbo协议详解',
                author: '@authorlove',
                dateStr: 'Jan 2nd, 2019',
                desc: '本文介绍常用的协议模式和 dubbo 协议的设计',
                link: '/zh-cn/blog/dubbo-protocol.html',
            },
            {
                title: '在 Dubbo 中使用 REST',
                author: '@beiwei30',
                dateStr: 'Jan 1st, 2019',
                desc: '本文介绍 REST 的基本概念，如何在 Dubbo 中开发 REST HTTP 应用，以及如何集成 Swagger',
                link: '/zh-cn/blog/dubbo-rest.html',
            },
            {
                title: 'Dubbo 上下文信息',
                author: '@guohao',
                dateStr: 'Dec 29th, 2018',
                desc: '本文介绍了Dubbo框架上下文信息的应用场景和使用方式。',
                link: '/zh-cn/blog/dubbo-context-information.html',
            },
            {
                title: 'Dubbo 博客文档中文排版指南',
                author: '@徐靖峰',
                dateStr: 'Dec 27th, 2018',
                desc: '统一中文文案、排版的相关用法，降低团队成员之间的沟通成本，增强网站气质。',
                link: '/zh-cn/blog/dubbo-copywriting-style.html',
            },
            {
                title: 'Dubbo 中的 URL 统一模型',
                author: '@徐靖峰',
                dateStr: 'Dec 27th, 2018',
                desc: 'URL 是 Dubbo 中一个重要的领域模型，了解它可以更加轻松的理解 Dubbo 的设计理念。',
                link: '/zh-cn/blog/introduction-to-dubbo-url.html',
            },
            {
                title: 'Dubbo 现有心跳方案总结以及改进建议',
                author: '@徐靖峰',
                dateStr: 'Jan 16th, 2019',
                desc: '一种心跳，两种设计',
                link: '/zh-cn/blog/dubbo-heartbeat-design.html',
            },
            {
                title: 'Dubbo 博客文档中文排版指南',
                author: '@徐靖峰',
                dateStr: 'Dec 27th, 2018',
                desc: '统一中文文案、排版的相关用法，降低团队成员之间的沟通成本，增强网站气质。',
                link: '/zh-cn/blog/dubbo-copywriting-style.html',
            },
            {
                title: '当Dubbo遇上Arthas：排查问题的实践',
                author: '@hengyunabc',
                dateStr: 'Dec 14th, 2018',
                desc: '本文介绍使用Alibaba开源的应用诊断利器Arthas来排查Dubbo应用的问题。',
                link: '/zh-cn/blog/dubbo-meet-arthas.html',
            },
            {
                title: 'Dubbo集群容错',
                author: '@ralf0131',
                dateStr: 'Dec 11th, 2018',
                desc: '本文介绍了Dubbo框架提供的多种错误处理策略，并通过实例说明如何进行配置。',
                link: '/zh-cn/blog/dubbo-cluster-error-handling.html',
            },
            {
                title: '在 Dubbo 中使用 Zipkin',
                author: '@beiwei30',
                dateStr: 'Oct 12th, 2018',
                desc: '本文介绍如何使用 Zipkin 在 Dubbo 中进行全链路追踪',
                link: '/zh-cn/blog/use-zipkin-in-dubbo.html',
            },
            {
                title: 'Dubbo在Service Mesh下的思考和方案',
                author: '@JeffLv',
                dateStr: 'Sep 25th, 2018',
                desc: 'Dubbo在Service Mesh下的思考和方案',
                link: '/zh-cn/blog/dubbo-mesh-in-thinking.html',
            },
            {
                title: 'Dubbo Mesh ｜ Service Mesh的实践与探索',
                author: '@liyun',
                dateStr: 'Sep 14th, 2018',
                desc: '本文介绍了Dubbo在Service Mesh方向的实践与探索',
                link: '/zh-cn/blog/dubbo-mesh-service-mesh-exploring.html',
            },
            {
                title: '遇见Dubbo',
                author: '@carryxyh',
                dateStr: 'Sep 7th, 2018',
                desc: '本文记录了一个小白成长为Dubbo committer的过程',
                link: '/zh-cn/blog/meet-dubbo.html',
            },
            {
                title: 'Dubbo 2.7.x repackage后的兼容实现方案',
                author: '@jerrick',
                dateStr: 'Sep 4th, 2018',
                desc: '本文简单描述了2.7.x repackage后对老版本的兼容性实现方案。',
                link: '/zh-cn/blog/dubbo-compatible.html',
            },
            {
                title: 'Dubbo与Kubernetes集成',
                author: '@kongming',
                dateStr: 'Sep 4th, 2018',
                desc: '本文主要尝试将Dubbo服务注册到Kubernetes，同时无缝融入kubernetes的多租户安全体系。',
                link: '/zh-cn/blog/dubbo-k8s.html',
            },
            {
                title: '如何参与贡献Dubbo开源',
                author: '@jerrick',
                dateStr: 'Sep 4th, 2018',
                desc: '本文介绍了如何以Apache Way的方式参与Dubbo社区并做贡献',
                link: '/zh-cn/blog/how-to-involve-dubbo-community.html',
            },
            {
                title: '使用Skywalking追踪Dubbo服务',
                author: '张鑫',
                dateStr: 'Sep 3nd, 2018',
                desc: '使用Skywalking追踪Dubbo服务',
                link: '/zh-cn/blog/tracing-with-skywalking.html',
            },
            {
                title: '如何准备Apache Release',
                author: 'Jun Liu',
                dateStr: 'Sep 2nd, 2018',
                desc: '如何准备Apache Release',
                link: '/zh-cn/blog/prepare-an-apache-release.html',
            },
            {
                title: 'Dubbo服务分组和版本聚合',
                author: '@nzomkxia',
                dateStr: 'August 29th, 2018',
                desc: '介绍了Dubbo中组别和版本的概念，以及如何一次调用多个版本，将结果聚合返回',
                link: '/zh-cn/blog/service-and-version.html',
            },
            {
                title: 'Dubbo测试验证',
                author: '@nzomkxia',
                dateStr: 'August 28th, 2018',
                desc: '介绍了Dubbo中的测试验证功能,方便在开发过程中进行测试',
                link: '/zh-cn/blog/test-verification.html',
            },
            {
                title: '以Dubbo为例，聊聊如何向开源项目做贡献',
                author: '@徐靖峰',
                dateStr: 'August 28th, 2018',
                desc: '开源从来不是高级开发者的专属词汇',
                link: '/zh-cn/blog/dubbo-contribue-to-opensource.html',
            },
            {
                title: 'Spring应用快速集成Dubbo + Hystrix',
                author: '@hengyunabc',
                dateStr: 'August 10th, 2018',
                desc: '本文介绍在spring应用里，怎么把Dubbo和Hystrix结合起来使用',
                link: '/zh-cn/blog/dubbo-integrate-with-hystrix.html',
            },
            {
                title: '如何基于Dubbo实现全异步调用链',
                author: '@chickenlj',
                dateStr: 'August 10th, 2018',
                desc: '本文回顾了 2.6.x 版本的异步实现，然后引出了 2.7.0 版本基于 CompletableFuture 的异步编程方式',
                link: '/zh-cn/blog/dubbo-new-async.html',
            },
            {
                title: 'Dubbo的负载均衡',
                author: '@vangoleo',
                dateStr: 'August 10th, 2018',
                desc: '本文介绍了负载均衡的相关概念以及 Dubbo 中的负载均衡策略实现',
                link: '/zh-cn/blog/dubbo-loadbalance.html',
            },
            {
                title: 'Dubbo的泛化调用',
                author: '@jerrick',
                dateStr: 'August 10th, 2018',
                desc: '本文介绍了 Dubbo 泛化调用的使用场景及相关示例',
                link: '/zh-cn/blog/dubbo-generic-invoke.html',
            },
            {
                title: '如何准备一次Apache发布',
                author: '@chickenlj',
                dateStr: 'August 8th, 2018',
                desc: '从如何搭建本地构建环境到如何发起投票，详细的介绍了Apache版本发布的完整流程',
                link: '/zh-cn/blog/prepare-an-apache-release.html',
            },
            {
                title: '在 Dubbo 应用中使用 Zookeeper',
                author: '@beiwei30',
                dateStr: 'August 3rd, 2018',
                desc: '介绍了 Zookeeper 的基本概念、用法，以及如何在 Dubbo 应用中使用 Zookeeper 作为注册中心。',
                link: '/zh-cn/blog/dubbo-zk.html',
            },
            {
                title: '通过QoS对服务进行动态控制',
                author: '@Huxing Zhang',
                dateStr: 'August 2nd, 2018',
                desc: '介绍了如何使用Dubbo的QoS功能对服务进行动态配置，以及相关的参数及配置方式。',
                link: '/zh-cn/blog/introduction-to-dubbo-qos.html',
            },
            {
                title: '在 Dubbo 中使用注解',
                author: '@beiwei30',
                dateStr: 'August 1st, 2018',
                desc: '介绍了如何使用注解方式而非 XML 方式来开发 Dubbo 应用，可以学习到如何使用 @EnableDubbo、@Service、@Reference 的用法。',
                link: '/zh-cn/blog/dubbo-annotation.html',
            },
            {
                title: '从跨语言调用到 dubbo2.js',
                author: '@徐靖峰',
                dateStr: 'July 27th, 2018',
                desc: '如何使用 dubbo2.js 进行跨语言的 dubbo 调用',
                link: '/zh-cn/blog/dubbo2-js.html',
            },
            {
                title: 'Sentinel 为 Dubbo 服务保驾护航',
                author: '@Eric Zhao',
                dateStr: 'July 24th, 2018',
                desc: '主要介绍了面向分布式服务架构的轻量级流量控制组件 Sentinel 以及在 Dubbo 中整合使用 Sentinel 的最佳实践。',
                link: '/zh-cn/blog/sentinel-introduction-for-dubbo.html',
            },
            {
                title: '使用Pinpoint做分布式跟踪',
                author: '@majinkai',
                dateStr: 'July 12th, 2018',
                desc: '利用Pinpoint对Dubbo分布式应用进行调用链跟踪与性能监控',
                link: '/zh-cn/blog/pinpoint.html',
            },
            {
                title: 'Dubbo 的同步与异步调用方式',
                author: '@Jerrick Zhu',
                dateStr: 'July 10th, 2018',
                desc: '主要讲述了 Dubbo 在底层异步通信机制的基础上实现的同步调用、异步调用、参数回调以及事件通知几种方式及示例。',
                link: '/zh-cn/blog/dubbo-invoke.html',
            },
            {
                title: '第一个Dubbo filter',
                author: '@nzomkxia',
                dateStr: 'July 1st, 2018',
                desc: '介绍了Dubbo中的filter机制，并且详细介绍了如何实现一个自己的Dubbo filter',
                link: '/zh-cn/blog/first-dubbo-filter.html',
            },
            {
                title: '第一个 Dubbo 应用',
                author: '@beiwei30',
                dateStr: 'June 2nd, 2018',
                desc: '现代的分布式服务框架的基本概念与 RMI 是类似的，同样是使用 Java 的 Interface 作为服务契约，通过注册中心来完成服务的注册和发现，远程通讯的细节也是通过代理类来屏蔽。',
                link: '/zh-cn/blog/dubbo-101.html',
            },
            {
                title: 'Dubbo基本用法之Provider配置',
                author: '@cvictory',
                dateStr: 'June 1st, 2018',
                desc: '主要讲述如何配置dubbo，按照配置方式上分，可以分为：XML配置，properties方式配置，注解方式配置，API调用方式配置。',
                link: '/zh-cn/blog/dubbo-basic-usage-dubbo-provider-configuration.html',
            },
              {
                title: '谷歌编程之夏会议上2018个项目被宣布',
                author: '@Jlele Cao',
                dateStr: 'April 25th，2018',
                desc: 'Raghu Reddy 的项目"Apache Dubbo 扩展串行协议支持" 被接受! 祝贺他!',
                link: '/zh-cn/blog/gsoc-2018.html',
            },
            {
                title: 'Spring Boot Dubbo应用启停源码分析',
                author: '@Huxing Zhang',
                dateStr: 'May 28th, 2018',
                desc: 'dubbo-spring-boot-project致力于简化 Dubbo RPC 框架在Spring Boot应用场景的开发，同时也整合了Spring Boot特性。',
                link: '/zh-cn/blog/spring-boot-dubbo-start-stop-analysis.html',
            },
            {
                title: '优化技巧：提前if判断帮助CPU分支预测',
                author: '@hengyunabc',
                dateStr: 'May 20th, 2018',
                desc: '要提高代码执行效率，一个重要的原则就是尽量避免CPU把流水线清空，那么提高分支预测的成功率就非常重要。那么对于代码里，如果某个switch分支概率很高，是否可以考虑代码层面帮CPU把判断提前，来提高代码执行效率呢？',
                link: '/zh-cn/blog/optimization-branch-prediction.html',
            },
            {
                title: 'Dubbo可扩展机制实战',
                author: '@vangoleo',
                dateStr: 'May 10th, 2018',
                desc: '在谈到软件设计时，可扩展性一直被谈起，那到底什么才是可扩展性，什么样的框架才算有良好的可扩展性呢？',
                link: '/zh-cn/blog/introduction-to-dubbo-spi.html',
            },
            {
                title: 'Dubbo可扩展机制源码解析',
                author: '@vangoleo',
                dateStr: 'May 10th, 2018',
                desc: '在前面的博客中，我们了解了Dubbo扩展机制的一些概念，初探了Dubbo中LoadBalance的实现，并自己实现了一个LoadBalance。接下来，我们就深入Dubbo的源码，一睹庐山真面目。',
                link: '/zh-cn/blog/introduction-to-dubbo-spi-2.html',
            }
        ]
    },
};
