# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      git submodule update --init --recursive
      npm install
      cd themes/docsy/ && npm install && cd ../../
      npm install -g hugo-extended
    command: hugo server --disableFastRender --bind=0.0.0.0 --port=1313 --baseURL=$(gp url 1313) --appendPort=false

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-browser
    visibility: public