DirectoryPath: public
IgnoreAltMissing: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
DocumentConcurrencyLimit: 1024
HTTPConcurrencyLimit: 256
ExternalTimeout: 15
LogLevel: 1
IgnoreURLs: [
  # starter not available => temp ignore
  "http://start.dubbo.io",
  # edit page => always ignore
  "https://github.com/apache/dubbo-website/edit/master/content/.*",
  # docs external link might temporally unavailable => always ignore
  "http://javatar.iteye.com/.*",
  "https://www.baeldung.com/bdd-mockito",
  "https://docs.github.com/.*",
  "https://apachecon.dukecon.org/acna/2018/#/scheduledEvent/b8db9dc580d85853f",
  "https://www.webjars.org/documentation#servlet3",
  "https://developer.aliyun.com/article/"]