DirectoryPath: public
IgnoreAltMissing: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
ExternalTimeout: 15
LogLevel: 1
IgnoreURLs: [
  # starter not available => temp ignore
  "http://start.dubbo.io",
  # edit page => always ignore
  "https://github.com/apache/dubbo-website/edit/master/content/.*",
  "https://github.com/apache/dubbo-website/new/master/content/.*",
  # docs external link might temporally unavailable => always ignore
  "http://javatar.iteye.com/.*",
  "https://www.baeldung.com/bdd-mockito",
  "https://docs.github.com/.*",
  "https://apachecon.dukecon.org/acna/2018/#/scheduledEvent/b8db9dc580d85853f",
  "https://www.yuque.com/docs/share/eff9c51f-a7f4-47d6-87ff-11a2152bdffe?",
  "https://www.webjars.org/documentation#servlet3",
  "https://developer.aliyun.com/article/"]