DirectoryPath: public
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreCanonicalBrokenLinks: false
ExternalTimeout: 15
LogLevel: 1
CacheExpires: 24h
IgnoreURLs: [
  # starter not available => temp ignore
  "http://start.dubbo.io",
  # mesh
  "https://github.com/apache/dubbo-go-samples/tree/f7febed9d686cb940ea55d34b5baa567d7574a44/route/meshroute",
  # edit page => always ignore
  "https://github.com/apache/dubbo-website/edit/master/content/.*",
  "https://github.com/apache/dubbo-website/new/master/content/.*",
  "https://github.com/apache/dubbo-website/tree/master/content/.*",
  "https://selfserve.apache.org",
  # docs external link might temporally unavailable => always ignore
  "https://d.sb/.*",
  "http://javatar.iteye.com/.*",
  "https://blog.csdn.net/.*",
  "https://www.baeldung.com/bdd-mockito",
  "https://docs.github.com/.*",
  "http://hessian.caucho.com/.*",
  "https://stackoverflow.com/.*",
  "http://stackoverflow.com/.*",
  "https://unix.stackexchange.com/.*",
  "https://doi.org/10.1145/3593856.3595909",
  "https://github.com/dubbo/awesome-dubbo/blob/master/slides/meetup/201812%40hangzhou/troubleshooting-dubbo-with-arthas.pdf",
  "https://apachecon.dukecon.org/acna/2018/#/scheduledEvent/b8db9dc580d85853f",
  "https://www.yuque.com/docs/share/eff9c51f-a7f4-47d6-87ff-11a2152bdffe?",
  "https://www.yuque.com/docs/share/c698bd6e-e4d6-47db-bc1c-c757cc9b4f3e?",
  "https://www.yuque.com/docs/share/c132d5db-0dcb-487f-8833-7c7732964bd4?#",
  "https://www.yuque.com/docs/share/f4e72670-74ab-45b9-bc0c-4b42249ed953?#",
  "https://www.oschina.net/question/3820517_2306822",
  "https://www.webjars.org/documentation#servlet3",
  "https://twitter.com/apachedubbo",
  "https://www.qianmi.com/",
  "https://developer.aliyun.com/article/",
  "https://www.gitlink.org.cn/glcc/freeproject",
  "https://zh.opensuse.org/.*"]
