title: Apache Dubbo (incubating)
description: a high-performance, java based, open source RPC framework
show_downloads: false
google_analytics: UA-112489517-1
theme: jekyll-theme-cayman
github:
    zip_url: https://github.com/apache/incubator-dubbo/zipball/master
    tar_url: https://github.com/apache/incubator-dubbo/tarball/master
    gitbook_url: books
    repository_url: https://github.com/apache/incubator-dubbo
    is_project_page: true