name: Website build

on:
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build
        run: |
          pip install \
              mkdocs-material>=5.5.3 \
              mkdocs-minify-plugin>=0.3 \
              mkdocs-redirects>=1.0
          mkdocs --version
          echo "removing previous static files from ./output" && rm -rf ./output
          mkdocs build -f mkdocs_en.yml -d ./output/en-us && mkdocs build -f mkdocs_zh.yml -d ./output/zh-cn
          mkdir deploy-dist && cp -R img ./output/zh-cn/ && cp -R img ./output/en-us/ && cp -R ./output/* deploy-dist/
          cp -R schema deploy-dist/
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: deploy-dist/